# Generated by Django 4.1.7 on 2023-11-18 07:40

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecturals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Architecturals')),
            ],
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Blueprints')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('work_planned', models.TextField(blank=True, max_length=500)),
                ('issues', models.TextField(blank=True, max_length=500)),
                ('workers_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_spendings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_achieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Legals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Legals')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='MEP')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('overdue', 'Overdue')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('designing', 'Designing'), ('approvals', 'Approvals'), ('ground_breaking', 'Ground Breaking'), ('substructure', 'Substructure'), ('superstructure', 'Superstructure'), ('finishes', 'Finishes'), ('handing_over', 'Handing Over')], default='designing', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('phases', models.CharField(choices=[('designing', 'Designing'), ('approvals', 'Approvals'), ('ground_breaking', 'Ground Breaking'), ('substructure', 'Substructure'), ('superstructure', 'Superstructure'), ('finishes', 'Finishes'), ('handing_over', 'Handing Over')], max_length=255)),
                ('current_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect_projects', to=settings.AUTH_USER_MODEL)),
                ('architecturals', models.ManyToManyField(blank=True, related_name='architecturals', to='projectmgt.architecturals')),
                ('blueprints', models.ManyToManyField(blank=True, related_name='blueprints', to='projectmgt.blueprint')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreman_projects', to=settings.AUTH_USER_MODEL)),
                ('legals', models.ManyToManyField(blank=True, related_name='legals', to='projectmgt.legals')),
                ('mep', models.ManyToManyField(blank=True, related_name='mep', to='projectmgt.mep')),
                ('payments', models.ManyToManyField(blank=True, related_name='project_payments', to='projectmgt.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField()),
                ('tags', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('isComplete', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('spendings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('workers_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField()),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='projectmgt.comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_task', to='projectmgt.project')),
            ],
        ),
        migrations.CreateModel(
            name='Structurals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Structurals')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_images', to='projectmgt.project')),
            ],
        ),
        migrations.CreateModel(
            name='Renders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Renders')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_images', to='projectmgt.project')),
            ],
        ),
        migrations.CreateModel(
            name='RecordPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Blueprints')),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmgt.dailyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='QS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='QS')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_images', to='projectmgt.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='qs',
            field=models.ManyToManyField(blank=True, related_name='qs', to='projectmgt.qs'),
        ),
        migrations.AddField(
            model_name='project',
            name='renders',
            field=models.ManyToManyField(blank=True, related_name='renders', to='projectmgt.renders'),
        ),
        migrations.AddField(
            model_name='project',
            name='structurals',
            field=models.ManyToManyField(blank=True, related_name='structurals', to='projectmgt.structurals'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmgt.project'),
        ),
        migrations.AddField(
            model_name='mep',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mep_images', to='projectmgt.project'),
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmgt.dailyrecord')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmgt.material')),
            ],
        ),
        migrations.AddField(
            model_name='legals',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_images', to='projectmgt.project'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('text', 'Text'), ('material', 'Material')], max_length=8)),
                ('content', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmgt.material')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoices', models.ManyToManyField(blank=True, related_name='invoices', to='projectmgt.invoiceitem')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmgt.project')),
            ],
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='records', to='projectmgt.recordpics'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='materials', to='projectmgt.materialusage'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmgt.project'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField()),
                ('square_feet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='projectmgt.project')),
            ],
        ),
        migrations.AddField(
            model_name='blueprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmgt.project'),
        ),
        migrations.AddField(
            model_name='architecturals',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectural_images', to='projectmgt.project'),
        ),
    ]
