# Generated by Django 4.1.7 on 2023-11-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
