# Generated by Django 4.1.7 on 2023-11-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmgt', '0002_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
